package com.bytmasoft.dm.enums;

public enum UploadType {
  USER_PROFILE_IMAGE,
  FOUND_ITEM_IMAGE,
  LOST_ITEM_IMAGE,
  FOUND_ITEM_DOCUMENT,
  LOST_ITEM_DOCUMENT,
  USER_DOCUMENT,
  FOUND_ITEM_THUMBNAIL,
  LOST_ITEM_THUMBNAIL,
  USER_PROFILE_THUMBNAIL,
  VEHICLE_PHOTO,
  VEHICLE_PHOTO_THUMBNAIL
}

